version: '3'
services:
  db:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data
    ports:
     - 5432:5432
      
  web:
    depends_on:
      - 'db'
    image: test/api
    command: bundle exec rails s -p 3000 -b '0.0.0.0' && bundle exec rake  db:migrate RAILS_ENV=development
    ports:
      - 3000:3000
    volumes:
      - .:/web

  angular:
    image: mfelgate/angular
    ports:
      - 80:80